apiVersion: apps/v1
kind: Deployment
metadata:
  name: masalashop-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: masalashop
  template:
    metadata:
      labels:
        app: masalashop
    spec:
      containers:
      - name: masalashop-container
        image: myconn.azurecr.io/masalashop:v1
        ports:
        - containerPort: 3000
